package com.zank.choiceness.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zank.choiceness.entity.NewsTypeInfo;
import com.zank.choiceness.entity.User;

import com.zank.choiceness.greendao.NewsTypeInfoDao;
import com.zank.choiceness.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsTypeInfoDaoConfig;
    private final DaoConfig userDaoConfig;

    private final NewsTypeInfoDao newsTypeInfoDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsTypeInfoDaoConfig = daoConfigMap.get(NewsTypeInfoDao.class).clone();
        newsTypeInfoDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        newsTypeInfoDao = new NewsTypeInfoDao(newsTypeInfoDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(NewsTypeInfo.class, newsTypeInfoDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        newsTypeInfoDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public NewsTypeInfoDao getNewsTypeInfoDao() {
        return newsTypeInfoDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
